#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LKADSDK_Example' do
  pod 'LKADSDK', :path => '../'

  target 'LKADSDK_Tests' do
    inherit! :search_paths

    
  end
end
